---
version: '3.3'
services:
  postgres-ui:
    image: postgres-ui:dont_push
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-ui
    hostname: postgres-ui
    restart: always
    environment:
      - VIRTUAL_HOST=postgres-ui.local
      - VIRTUAL_PORT=8081
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres-15-1:5432/postgres?sslmode=disable
    expose:
      - 8081
    networks:
      - local
    depends_on:
      - postgres-15-1
networks:
  local:
    name: local
