---
version: '3.3'
services:
  otel-collector-0-86-0:
    image: ${PULL_THRU_CACHE}otel/opentelemetry-collector-contrib:0.86.0
    container_name: otel-collector-0-86-0
    hostname: otel-collector-0-86-0
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    expose:
      - "1888"  # pprof extension
      - "8888"  # Prometheus metrics exposed by the collector
      - "8889"  # Prometheus exporter metrics
      - "13133"  # health_check extension
      - "4317"  # OTLP gRPC receiver
      - "55679"  # zpages extension
    networks:
      - local_network
networks:
  local_network:
    name: local_network
