---
version: '3.3'
services:
  timescaledb-2-9-1-pg15:
    image: ${PULL_THRU_CACHE}timescale/timescaledb:2.9.1-pg15
    container_name: timescaledb-2-9-1-pg15
    hostname: timescaledb-2-9-1-pg15
    restart: always
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    expose:
      - 5432
    networks:
      - local_backend
    healthcheck:
      test: psql -h 127.0.0.1 -U postgres -c 'select 1;'
      interval: 5s
      timeout: 4s
      retries: 36
  timescaledb_ui:
    image: ${PULL_THRU_CACHE}sosedoff/pgweb:0.11.12
    container_name: timescaledb-ui
    hostname: timescaledb-ui
    restart: always
    environment:
      - VIRTUAL_HOST=timescaledb-ui.local
      - VIRTUAL_PORT=8081
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@timescaledb-2-9-1-pg15:5432/postgres?sslmode=disable
    networks:
      - local_backend
    depends_on:
      - timescaledb-2-9-1-pg15
networks:
  local_backend:
    name: local_backend
