---
version: '3.3'
services:
  jaeger-all-in-one:
    image: jaeger-all-in-one:dont_push
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jaeger-all-in-one
    hostname: jaeger-all-in-one
    restart: always
    environment:
      - VIRTUAL_HOST=jaeger.local
      - VIRTUAL_PORT=16686
    expose:
      - 16686
      - 14268
      - 14250
    networks:
      - local
networks:
  local:
    name: local
