---
version: '3.3'
services:
  nginx-proxy:
    image: ${PULL_THRU_CACHE}jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    hostname: nginx-proxy
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
    networks:
      - local_network
    healthcheck:
      test: nc -zv 127.0.0.1 80
      interval: 5s
      timeout: 4s
      retries: 36
networks:
  local_network:
    name: local_network
