---
version: '3.3'
services:
  nginx_proxy:
    image: ${PULL_THRU_CACHE}jwilder/nginx-proxy:alpine
    container_name: nginx_proxy
    hostname: nginx_proxy
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
    networks:
      - local_backend
networks:
  local_backend:
    external:
      name: local_backend
