---
version: '3.3'
services:
  gitea:
    image: ${PULL_THRU_CACHE}gitea/gitea:1.18.3
    container_name: gitea-1-18-3
    hostname: gitea-1-18-3
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-postgres-15-1:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=postgres
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
      - ROOT_URL=http://gitea.local
      - VIRTUAL_HOST=gitea.local
      - VIRTUAL_PORT=3000
    expose:
      - 3000
      - 22
    ports:
      - 8222:22
    networks:
      - local_backend
    depends_on:
      - gitea-db
  gitea-db:
    image: ${PULL_THRU_CACHE}library/postgres:15.1-alpine3.17
    container_name: gitea-postgres-15-1
    hostname: gitea-postgres-15-1
    restart: always
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=gitea"
    expose:
      - 5432
    networks:
      - local_backend
    healthcheck:
      test: psql -h 127.0.0.1 -U postgres -c 'select 1;'
      interval: 5s
      timeout: 4s
      retries: 36
networks:
  local_backend:
    name: local_backend
