---
version: '3.3'
services:
  alertmanager-0-26-0:
    image: alertmanager-0-26-0:dont_push
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alertmanager-0-26-0
    hostname: alertmanager-0-26-0
    restart: always
    expose:
      - 9093
    environment:
      - VIRTUAL_HOST=alertmanager.local
      - VIRTUAL_PORT=9093
    networks:
      - local
networks:
  local:
    name: local
