---
version: '3.3'
services:
  redis-7-0-5:
    image: ${PULL_THRU_CACHE}library/redis:7.0.5-alpine3.16
    container_name: redis-7-0-5
    hostname: redis-7-0-5
    restart: always
    expose:
      - 6379
    networks:
      - local
    healthcheck:
      test: redis-cli -h 127.0.0.1 -p 6379 PING
      interval: 5s
      timeout: 4s
      retries: 36
networks:
  local:
    name: local
