---
version: '3.3'
services:
  grafana-10-1-4:
    image: grafana-10-1-4:dont_push
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grafana-10-1-4
    hostname: grafana-10-1-4
    restart: always
    volumes:
      - ./datasources-provisioning.yml:/etc/grafana/provisioning/datasources/all.yml:ro
      - ./dashboards-provisioning.yml:/etc/grafana/provisioning/dashboards/local.yml:ro
      - ./my-run.sh:/my-run.sh
    entrypoint: /my-run.sh
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=grafana.local
      - VIRTUAL_PORT=3000
    networks:
      - local
networks:
  local:
    name: local
