---
version: '3.3'
services:
  gitea-db:
    image: ${PULL_THRU_CACHE}library/postgres:15.1-alpine3.17
    container_name: gitea-db
    hostname: gitea-db
    restart: always
    volumes:
      - ./healthcheck.sh:/healthcheck.sh
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=gitea"
    expose:
      - 5432
    networks:
      - local
    healthcheck:
      test: psql -h 127.0.0.1 -U postgres -c 'select 1;'
      interval: 5s
      timeout: 4s
      retries: 36
networks:
  local:
    name: local
