---
version: '3.3'
services:
  gitea-1-18-3:
    image: gitea-1-18-3:dont_push
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gitea-1-18-3
    hostname: gitea-1-18-3
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-postgres-15-1:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=postgres
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
      - ROOT_URL=http://gitea.local
      - VIRTUAL_HOST=gitea.local
      - VIRTUAL_PORT=3000
    expose:
      - 3000
      - 22
    ports:
      - 8222:22
    networks:
      - local
networks:
  local:
    name: local
