---
version: '3.3'
services:
  prometheus-2-47-0:
    image: prometheus-2-47-0:dont_push
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prometheus-2-47-0
    hostname: prometheus-2-47-0
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - 9090
    environment:
      - VIRTUAL_HOST=prometheus.local
      - VIRTUAL_PORT=9090
    networks:
      - local
networks:
  local:
    name: local
