---
version: '3.3'
services:
  zipkin-all-in-one:
    image: zipkin-all-in-one:dont_push
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zipkin-all-in-one
    hostname: zipkin-all-in-one
    restart: always
    environment:
      - VIRTUAL_HOST=zipkin.local
      - VIRTUAL_PORT=9411
    expose:
      - 9411
    networks:
      - local
networks:
  local:
    name: local
