---
version: '3.3'
services:
  postgres:
    image: ${PULL_THRU_CACHE}library/postgres:15.1-alpine3.17
    container_name: postgres-15-1
    hostname: postgres-15-1
    restart: always
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    #ports:
      # - 5432:5432
    expose:
      - 5432
    networks:
      - local_backend
    healthcheck:
      test: psql -h 127.0.0.1 -U postgres -c 'select 1;'
      interval: 5s
      timeout: 4s
      retries: 36
networks:
  local_backend:
    name: local_backend
