---
version: '3.3'
services:
  postgres-15-1:
    image: ${PULL_THRU_CACHE}library/postgres:15.1-alpine3.17
    container_name: postgres-15-1
    hostname: postgres-15-1
    restart: always
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    #ports:
      # - 5432:5432
    expose:
      - 5432
    networks:
      - local
    #healthcheck:
    #  test: psql -h 127.0.0.1 -U postgres -c 'select 1;'
    #  interval: 5s
    #  timeout: 4s
    #  retries: 36
#  postgres-ui:
#    image: ${PULL_THRU_CACHE}sosedoff/pgweb:0.11.12
#    container_name: postgres-ui
#    hostname: postgres-ui
#    restart: always
#    environment:
#      - VIRTUAL_HOST=postgres-ui.local
#      - VIRTUAL_PORT=8081
#      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres-15-1:5432/postgres?sslmode=disable
#    expose:
#      - 8081
#    networks:
#      - local
#    depends_on:
#      - postgres-15-1
networks:
  local:
    name: local
