---
version: '3.3'
services:
  nginx:
    image: ${PULL_THRU_CACHE}library/nginx:alpine
    #image: docker.io/ibrary/nginx:alpine
    container_name: nginx
    hostname: nginx
    restart: always
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
      - local
    #healthcheck:
    #  test: nc -zv 127.0.0.1 80
    #  interval: 5s
    #  timeout: 4s
    #  retries: 36
networks:
  local:
    name: local
