---
version: '3.3'
services:
  elasticsearch-oss-7-10-2:
    image: elasticsearch-oss-7-10-2:dont_push
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elasticsearch-oss-7-10-2
    hostname: elasticsearch-oss-7-10-2
    restart: always
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"
    expose:
      # REST
      - 9200/tcp
      # Transport
      - 9300/tcp
      # Performance Analyzer
      - 9600/tcp
    networks:
      - local
networks:
  local:
    name: local
