---
version: '3.3'
services:
  timescaledb-2-9-1:
    image: ${PULL_THRU_CACHE}timescale/timescaledb:2.9.1-pg15
    container_name: timescaledb-2-9-1
    hostname: timescaledb-2-9-1
    restart: always
    volumes:
      - ./healthcheck.sh:/healthcheck.sh
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    expose:
      - 5432
    networks:
      - local
    healthcheck:
      test: psql -h 127.0.0.1 -U postgres -c 'select 1;'
      interval: 5s
      timeout: 4s
      retries: 36
networks:
  local:
    name: local
