---
version: '3.3'
services:
  postgis-15-3-3:
    image: ${PULL_THRU_CACHE}postgis/postgis:15-3.3-alpine
    container_name: postgis-15-3-3
    hostname: postgis-15-3-3
    restart: always
    volumes:
      - ./healthcheck.sh:/healthcheck.sh
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    #ports:
      #- 5432:5432
    expose:
      - 5432
    networks:
      - local
    #healthcheck:
    #  test: psql -h 127.0.0.1 -U postgres -c 'select 1;'
    #  interval: 5s
    #  timeout: 4s
    #  retries: 36
  postgis-ui:
    image: ${PULL_THRU_CACHE}sosedoff/pgweb:0.11.12
    container_name: postgis-ui
    hostname: postgis-ui
    restart: always
    environment:
      - VIRTUAL_HOST=postgis-ui.local
      - VIRTUAL_PORT=8081
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgis-15-3-3:5432/postgres?sslmode=disable
    expose:
      - 8081
    networks:
      - local
    depends_on:
      - postgis-15-3-3
networks:
  local:
    name: local
