---
version: '3.3'
services:
  postgis_15_3_3:
    image: ${PULL_THRU_CACHE}postgis/postgis:15-3.3-alpine
    container_name: postgis_15_3_3
    hostname: postgis_15_3_3
    restart: always
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    expose:
      - 5432
    networks:
      - local_backend
    healthcheck:
      test: psql -h 127.0.0.1 -U postgres -c 'select 1;'
      interval: 5s
      timeout: 4s
      retries: 36
  postgis_ui:
    image: ${PULL_THRU_CACHE}sosedoff/pgweb:0.11.12
    container_name: postgis_ui
    hostname: postgis_ui
    restart: always
    environment:
      - VIRTUAL_HOST=postgis-ui.local
      - VIRTUAL_PORT=8081
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgis_15_3_3:5432/postgres?sslmode=disable
    networks:
      - local_backend
    depends_on:
      - postgis_15_3_3
networks:
  local_backend:
    external:
      name: local_backend
