---
version: '3.3'
services:
  zookeeper:
    image: ${PULL_THRU_CACHE}bitnami/zookeeper:3.8
    container_name: zookeeper-3-8
    hostname: zookeeper-3-8
    restart: always
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    expose:
      - 2181
    networks:
      - local
  kafka:
    image: ${PULL_THRU_CACHE}bitnami/kafka:3.3
    container_name: kafka-3-3
    hostname: kafka-3-3
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-3-8:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    expose:
      - 9092
    networks:
      - local
    depends_on:
      - zookeeper
  kafka-ui:
    image: ${PULL_THRU_CACHE}provectuslabs/kafka-ui:5f232a3966cda70eac34aa2b32ec4a610404d1c6
    container_name: kafka-ui
    hostname: kafka-ui
    restart: always
    environment:
      - VIRTUAL_HOST=kafka-ui.local
      - VIRTUAL_PORT=8080
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-3-3:9092
    networks:
      - local
networks:
  local:
    name: local
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
