---
version: '3.3'
services:
  cadvisor-0-47-2:
    image: cadvisor-0-47-2:dont_push
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cadvisor-0-47-2
    hostname: cadvisor-0-47-2
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/containerd/:/var/lib/containerd:ro
    expose:
      - 8080
    networks:
      - local
networks:
  local:
    name: local
