---
version: '3.3'
services:
  rabbitmq-3-11-3:
    image: ${PULL_THRU_CACHE}library/rabbitmq:3.11.3-alpine
    container_name: rabbitmq-3-11-3
    hostname: rabbitmq-3-11-3
    restart: always
    networks:
      - local_backend
  rabbitmq-ui:
    image: ${PULL_THRU_CACHE}library/rabbitmq:3-management
    container_name: rabbitmq-ui
    hostname: rabbitmq-ui
    restart: always
    environment:
      - VIRTUAL_HOST=rabbitmq-ui.local
      - VIRTUAL_PORT=15672
      - RABBITMQ_DEFAULT_VHOST=rabbitmq-ui.local
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - local_backend
networks:
  local_backend:
    name: local_backend
