---
version: '3.3'
services:
  xxljob-2-3-1:
    image: xxljob:dont_push
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xxljob-2-3-1
    hostname: xxljob-2-3-1
    restart: always
    environment:
      - VIRTUAL_HOST=xxljob.local
      - VIRTUAL_PORT=8080
      - "PARAMS=--spring.datasource.url=jdbc:mysql://root:hello123@mysql-8-0-31:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai"
    expose:
      - 8080
    networks:
      - local
networks:
  local:
    name: local
